### ISSUE TITLE
highlight and annotate

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/Academic_Media#2]
- View the entire new article.
- Researcher can highlight part of the news article and "annotate"  add a comment, to the highlighted text.
- in "view" mode like what the research subject would see, the article is shown with highlighted text, then when the user hovers over the highlighting, the annotation is shown.
- have a view option in the Researcher view to test this.

**Comment by karthicksakkaravarti** [comment]
Completed. but couldn't get an entire new article from newsapi

**Comment by karthicksakkaravarti** [comment]
Completed. but couldn't get an entire new article from newsapi
